# Generated by Django 5.2.2 on 2025-06-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Unit_Name', models.CharField(max_length=100)),
                ('IsActive', models.BooleanField(default=True)),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('Unit_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Unit_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
