# Generated by Django 5.2.2 on 2025-06-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='NTID',
            field=models.CharField(default='default_ntid', max_length=15),
            preserve_default=False,
        ),
    ]
