# Generated by Django 5.2.2 on 2025-07-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloapp', '0003_employee_groups_employee_is_active_employee_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
